'use client';

import React, { useState, useEffect } from 'react';
import { setDeviceToken } from '@/lib/device-auth';

/**
 * PairDevice — shown when the app loads on /pair (see AegisAgent's pairing
 * URL, generated by POST /api/pair/start). Lets a new device redeem a
 * short-lived OTP for a long-lived device token, then hands off to the
 * normal dashboard.
 */
export default function PairDevice() {
  const [code, setCode] = useState('');
  const [label, setLabel] = useState('');
  const [status, setStatus] = useState('idle'); // idle | pairing | success | error
  const [message, setMessage] = useState('');

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const prefilled = params.get('code');
    if (prefilled) setCode(prefilled.toUpperCase());
  }, []);

  const handlePair = async () => {
    if (!code.trim()) return;
    setStatus('pairing');
    setMessage('');
    try {
      const res = await fetch('/api/pair/redeem', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: code.trim().toUpperCase(), label: label.trim() || undefined }),
      });
      const data = await res.json();
      if (!data.success) {
        setStatus('error');
        setMessage(data.message || 'Pairing failed.');
        return;
      }
      setDeviceToken(data.device.token);
      setStatus('success');
      setTimeout(() => { window.location.href = '/'; }, 1200);
    } catch (e) {
      setStatus('error');
      setMessage('Could not reach the server. Check the connection and try again.');
    }
  };

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      height: '100vh', padding: '24px', background: 'var(--bg-base)', color: 'var(--text-primary)',
    }}>
      <div style={{
        width: '100%', maxWidth: '360px', display: 'flex', flexDirection: 'column', gap: '16px',
        background: 'var(--surface-elevated)', border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)', padding: '28px', boxShadow: '0 8px 32px -8px rgba(0,0,0,0.3)',
      }}>
        <div>
          <div style={{ fontSize: '1.1rem', fontWeight: 700 }}>Connect this device</div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginTop: '4px' }}>
            Enter the pairing code shown on your already-connected device.
          </div>
        </div>

        <div>
          <label style={{ display: 'block', fontSize: '0.72rem', color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '4px' }}>
            PAIRING CODE
          </label>
          <input
            value={code}
            onChange={(e) => setCode(e.target.value.toUpperCase())}
            placeholder="e.g. AB3XK9"
            maxLength={6}
            style={{
              width: '100%', height: '40px', padding: '0 12px', fontSize: '1rem', letterSpacing: '0.15em',
              textAlign: 'center', fontFamily: 'var(--font-mono)', textTransform: 'uppercase',
              background: 'var(--surface-primary)', border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-sm)', color: 'var(--text-primary)',
            }}
          />
        </div>

        <div>
          <label style={{ display: 'block', fontSize: '0.72rem', color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '4px' }}>
            DEVICE NAME (OPTIONAL)
          </label>
          <input
            value={label}
            onChange={(e) => setLabel(e.target.value)}
            placeholder="e.g. My Laptop"
            style={{
              width: '100%', height: '36px', padding: '0 12px', fontSize: '0.85rem',
              background: 'var(--surface-primary)', border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-sm)', color: 'var(--text-primary)',
            }}
          />
        </div>

        {message && (
          <div style={{
            fontSize: '0.78rem',
            color: status === 'error' ? 'var(--accent-danger)' : 'var(--accent-success)',
          }}>
            {message}
          </div>
        )}

        <button
          onClick={handlePair}
          disabled={status === 'pairing' || status === 'success' || !code.trim()}
          style={{
            height: '40px', borderRadius: 'var(--radius-sm)', border: 'none',
            background: 'var(--accent-primary)', color: '#fff', fontWeight: 600, fontSize: '0.85rem',
            cursor: status === 'pairing' ? 'wait' : 'pointer',
            opacity: !code.trim() ? 0.5 : 1,
          }}
        >
          {status === 'success' ? 'Connected — redirecting...' : status === 'pairing' ? 'Connecting...' : 'Connect'}
        </button>
      </div>
    </div>
  );
}
