// @ts-nocheck
'use client';

import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { setDeviceToken } from '@/lib/device-auth';

/**
 * PairDevice — shown when the app loads on /pair (see Orbit's pairing
 * URL, generated by POST /api/pair/start). Lets a new device redeem a
 * short-lived OTP for a long-lived device token, then hands off to the
 * normal dashboard.
 */
export default function PairDevice() {
  const [code, setCode] = useState('');
  const [label, setLabel] = useState('');
  const [status, setStatus] = useState('idle'); // idle | pairing | success | error
  const [message, setMessage] = useState('');

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const prefilled = params.get('code');
    if (prefilled) setCode(prefilled.toUpperCase());
  }, []);

  const handlePair = async () => {
    if (!code.trim()) return;
    setStatus('pairing');
    setMessage('');
    try {
      const res = await fetch('/api/pair/redeem', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: code.trim().toUpperCase(), label: label.trim() || undefined }),
      });
      const data = await res.json();
      if (!data.success) {
        setStatus('error');
        setMessage(data.message || 'Pairing failed.');
        return;
      }
      setDeviceToken(data.device.token);
      setStatus('success');
      setTimeout(() => { window.location.href = '/'; }, 1200);
    } catch {
      setStatus('error');
      setMessage('Could not reach the server. Check the connection and try again.');
    }
  };

  return (
    <div className="flex h-screen flex-col items-center justify-center bg-background p-6 text-foreground">
      <div className="flex w-full max-w-[360px] flex-col gap-4 rounded-xl border border-border bg-card p-7 shadow-xl">
        <div>
          <div className="text-lg font-bold">Connect this device</div>
          <div className="mt-1 text-sm text-muted-foreground">
            Enter the pairing code shown on your already-connected device.
          </div>
        </div>

        <div>
          <label className="mb-1 block text-xs font-semibold text-muted-foreground">PAIRING CODE</label>
          <Input
            value={code}
            onChange={(e) => setCode(e.target.value.toUpperCase())}
            placeholder="e.g. AB3XK9"
            maxLength={6}
            className="h-10 text-center font-mono text-base uppercase tracking-widest"
          />
        </div>

        <div>
          <label className="mb-1 block text-xs font-semibold text-muted-foreground">DEVICE NAME (OPTIONAL)</label>
          <Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="e.g. My Laptop" className="h-9 text-sm" />
        </div>

        {message && (
          <div className={`text-[0.78rem] ${status === 'error' ? 'text-destructive' : 'text-success'}`}>{message}</div>
        )}

        <Button onClick={handlePair} disabled={status === 'pairing' || status === 'success' || !code.trim()} className="h-10">
          {status === 'success' ? 'Connected — redirecting...' : status === 'pairing' ? 'Connecting...' : 'Connect'}
        </Button>
      </div>
    </div>
  );
}
